package de.innologic.companyservice.domain;

public enum ErrorCode {
    MAIN_LOCATION_REQUIRED,
    MAIN_LOCATION_MUST_BE_OPEN,
    CANNOT_CLOSE_MAIN_LOCATION,
    CANNOT_TRASH_MAIN_LOCATION,
    LAST_OPEN_LOCATION_REQUIRED,
    COMPANY_TRASHED_OPERATION_NOT_ALLOWED,
    OPTIMISTIC_LOCK_FAILED,
    VALIDATION_FAILED,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    LOCATION_NOT_IN_COMPANY,
    INTERNAL_ERROR
}
